@MentorConnectAPI_HostAddress = https://localhost:5000
@courseId = 6d7910af-cd6c-48bc-8072-c03e79870e38
@categoryId = c1df4156-1bfa-4310-8ee1-b07c3a6159fc
@resourceId = 09d85232-fb4d-486a-a897-0710229a0318

### Authorize
POST {{MentorConnectAPI_HostAddress}}/api/Auth/sign-in
Accept: application/json
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%

 client.global.set("auth_token", response.body.value); 

%}

### GetAllCourse
GET {{MentorConnectAPI_HostAddress}}/api/Course?pageIndex=1&pageSize=10
Accept: application/json
Authorization: Bearer {{auth_token}}

### GetAllCourse with keyword > 256 should fail
GET {{MentorConnectAPI_HostAddress}}/api/Course?pageIndex=1&pageSize=10&keyword={{$random.alphanumeric(257)}}
Accept: application/json
Authorization: Bearer {{auth_token}}

### PostCourse
POST {{MentorConnectAPI_HostAddress}}/api/Course
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "{{$random.book.title}}",
  "description": "{{$random.lorem.sentence}}",
  "categoryId": "{{categoryId}}",
  "mentorId": "01047f62-6e87-442b-b1e8-2a54c9e17d7c",
  "dueDate": "{{$isoTimestamp}}",
  "tags": ["thrilling", "adventure"],
  "difficulty": "Beginner"
}

### GetCourseById
GET {{MentorConnectAPI_HostAddress}}/api/Course/{{courseId}}
Accept: application/json
Authorization: Bearer {{auth_token}}

### PutCourse
PUT {{MentorConnectAPI_HostAddress}}/api/Course/{{courseId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{ 
  "id": "{{courseId}}", 
  "title": "Updated Course Title",
  "description": "An updated description",
  "categoryId": "{{categoryId}}",
  "dueDate": "{{$isoTimestamp}}",
  "tags": ["thrilling", "Adventure", "{{$random.hacker.adjective}}"],
  "difficulty": "Beginner"
}

### DeleteCourse
DELETE {{MentorConnectAPI_HostAddress}}/api/Course/{{courseId}}
Accept: application/json
Authorization: Bearer {{auth_token}}

### PublishCourse
PUT {{MentorConnectAPI_HostAddress}}/api/Course/{{courseId}}/publish
Accept: application/json
Authorization: Bearer {{auth_token}}

### ArchiveCourse
PUT {{MentorConnectAPI_HostAddress}}/api/Course/{{courseId}}/archive
Accept: application/json
Authorization: Bearer {{auth_token}}

### GetAllCourseItems
GET {{MentorConnectAPI_HostAddress}}/api/Course/{{courseId}}/resource
Accept: application/json
Authorization: Bearer {{auth_token}}

### GetCourseItemById
GET {{MentorConnectAPI_HostAddress}}/api/Course/{{courseId}}/resource/{{resourceId}}
Accept: application/json
Authorization: Bearer {{auth_token}}

### CreateCourseItem
POST {{MentorConnectAPI_HostAddress}}/api/Course/{{courseId}}/resource
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "Introduction Video",
  "description": "Watch this introductory video to understand the course basics",
  "mediaType": "Video",
  "webAddress": "https://example.com/intro-video"
}

### UpdateCourseItem
PUT {{MentorConnectAPI_HostAddress}}/api/Course/{{courseId}}/resource/{{resourceId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "Updated Resource",
  "description": "Updated resource description",
  "mediaType": "pdf",
  "webAddress": "https://example.com/updated-resource"
}

### DeleteCourseItem
DELETE {{MentorConnectAPI_HostAddress}}/api/Course/{{courseId}}/resource/{{resourceId}}
Accept: application/json
Authorization: Bearer {{auth_token}}