@MentorConnectAPI_HostAddress = http://localhost:5127
@courseId = 2c330f36-9bf0-49dd-8ce9-c0c20cd0ddb6
### GetAllCourse
GET {{MentorConnectAPI_HostAddress}}/api/Course
Accept: application/json

### PostCourse
POST {{MentorConnectAPI_HostAddress}}/api/Course
Accept: application/json
Content-Type: application/json

{
  "title": "New Course Title",
  "description": "A description of the new course",
  "categoryId": "3144da58-deaa-4bf7-a777-cd96e7f1e3b1",
  "mentorId": "BC7CB279-B292-4CA3-A994-9EE579770DBE",
  "dueDate": "{{$isoTimestamp}}",
  "difficulty": "Beginner"
}

### GetCourseById
GET {{MentorConnectAPI_HostAddress}}/api/Course/{{courseId}}
Accept: application/json

### PutCourse
PUT {{MentorConnectAPI_HostAddress}}/api/Course/{{courseId}}
Accept: application/json
Content-Type: application/json

{ 
  "id": "{{courseId}}", 
  "title": "Updated Course Title",
  "description": "An updated description",
  "categoryId": "3144da58-deaa-4bf7-a777-cd96e7f1e3b1"
 
}

### DeleteCourse
DELETE {{MentorConnectAPI_HostAddress}}/api/Course/{{courseId}}
Accept: application/json