@MentorConnectAPI_HostAddress = https://localhost:5000

### Authorize as Admin
POST {{MentorConnectAPI_HostAddress}}/api/Auth/sign-in
Accept: application/json
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%

 client.global.set("auth_token", response.body.value.token);

%}

### Get Available Time Slot of all Mentor
GET {{MentorConnectAPI_HostAddress}}/api/SessionBooking/available-timeslots?pageIndex={{pageIndex}}&
    pageSize={{pageSize}}
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get Available Time Slot of a Mentor
GET {{MentorConnectAPI_HostAddress}}/api/SessionBooking/available-timeslots/{{mentorId}}?pageIndex={{pageIndex}}&
    pageSize={{pageSize}}
Accept: application/json
Authorization: Bearer {{auth_token}}
