export const PAGE_ENDPOINT_URL = {
  LOGIN: "/login",
  CATEGORIES: "/categories",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  SIGN_UP: "/signup",
  VIEW_PROFILE: "/profile",
  COURSE_MANAGEMENT: '/courses',
  AVAILABILITY: '/availability',
  STATUS_TRACKING: "/my-applications",
  APPLICATIONS: "/applications",
  RESOURCE: "/resources",
  DASHBOARD: "/dashboard",
  SESSION_BOOKING:'sessions',
  SESSION_TRACKING: 'sessions-tracking',
};
