import type { Course, CourseFormDataOptions } from "./types.tsx";

export type CourseStates = "draft" | "published" | "archived";
export const CourseStatesEnumMember: Record<CourseStates, string> = {
  draft: "Draft",
  published: "Published",
  archived: "Archived",
};

export type CourseLevel = "beginner" | "intermediate" | "advanced";
export const CourseLevelEnumMember: Record<CourseLevel, string> = {
  beginner: "Beginner",
  intermediate: "Intermediate",
  advanced: "Advanced",
};

export type CourseMimeType = "application/pdf" | "application/octet-stream";
export const CourseMediaTypeEnumMember: Record<CourseMimeType, string> = {
  "application/pdf": "pdf",
  "application/octet-stream": "binary",
};

export const initialFormData: CourseFormDataOptions = {
  title: "",
  description: "",
  categoryId: "",
  status: "draft",
  dueDate: "",
  difficulty: "beginner",
  tags: [],
};

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "Introduction to Leadership",
    description:
      "Learn fundamental leadership principles and develop your leadership style",
    categoryId: "1",
    categoryName: "Leadership Coaching",
    createdAt: "2024-09-15",
    updatedAt: "2024-11-02",
    status: "published",
    enrolledStudents: 24,
    completionRate: 78,
    dueDate: "6 weeks",
    difficulty: "beginner",
    tags: ["leadership", "beginner"],
    materials: [
      {
        id: "101",
        name: "Leadership Basics.pdf",
        mediaType: "pdf",
        url: "/resources/leadership-basics.pdf",
        uploadedAt: "2024-09-15",
      },
      {
        id: "102",
        name: "Communication Skills.pdf",
        mediaType: "pdf",
        url: "/resources/communication-skills.pdf",
        uploadedAt: "2024-09-20",
      },
    ],
    mentorId: "101",
    feedback: [],
  },
  {
    id: "2",
    title: "Advanced Leadership Strategies",
    description:
      "Master advanced leadership techniques for managing complex teams",
    categoryId: "1",
    categoryName: "Leadership Coaching",
    mentorName: "Joe",
    createdAt: "2024-10-05",
    updatedAt: "2024-10-28",
    status: "published",
    enrolledStudents: 18,
    completionRate: 62,
    dueDate: "8 weeks",
    difficulty: "advanced",
    tags: ["leadership", "advanced"],
    materials: [],
    mentorId: "102",
    feedback: [],
  },
  {
    id: "3",
    title: "Resume Building Workshop",
    description: "Create a standout resume that gets you noticed by employers",
    categoryId: "2",
    categoryName: "Career Development",
    createdAt: "2024-08-22",
    updatedAt: "2024-10-15",
    status: "published",
    enrolledStudents: 35,
    completionRate: 91,
    dueDate: "3 weeks",
    difficulty: "beginner",
    tags: ["resume", "career"],
    materials: [],
    mentorId: "103",
    feedback: [],
  },
  {
    id: "4",
    title: "Effective Project Management",
    description: "Learn to plan, execute, and close projects successfully",
    categoryId: "3",
    categoryName: "Project Management",
    createdAt: "2024-09-01",
    updatedAt: "2024-10-30",
    status: "published",
    enrolledStudents: 30,
    completionRate: 85,
    dueDate: "7 weeks",
    difficulty: "intermediate",
    tags: ["project management"],
    materials: [],
    mentorId: "104",
    feedback: [],
  },
  {
    id: "5",
    title: "Public Speaking Fundamentals",
    description: "Overcome fear and deliver compelling presentations",
    categoryId: "4",
    categoryName: "Public Speaking",
    createdAt: "2024-09-10",
    updatedAt: "2024-11-01",
    status: "published",
    enrolledStudents: 42,
    completionRate: 75,
    dueDate: "4 weeks",
    difficulty: "beginner",
    tags: ["public speaking"],
    materials: [],
    mentorId: "105",
    feedback: [],
  },
  {
    id: "7",
    title: "Resolving Workplace Conflict",
    description: "Learn strategies for navigating and resolving conflict",
    categoryId: "6",
    categoryName: "Conflict Resolution",
    createdAt: "2024-09-25",
    updatedAt: "2024-10-18",
    status: "published",
    enrolledStudents: 28,
    completionRate: 70,
    dueDate: "5 weeks",
    difficulty: "intermediate",
    tags: ["conflict resolution"],
    materials: [],
    mentorId: "107",
    feedback: [],
  },
  {
    id: "8",
    title: "Negotiation Skills for Success",
    description: "Develop strong negotiation skills for various situations",
    categoryId: "1", // Another Leadership Coaching course
    categoryName: "Leadership Coaching",
    createdAt: "2024-10-12",
    updatedAt: "2024-11-05",
    status: "published",
    enrolledStudents: 20,
    completionRate: 68,
    dueDate: "6 weeks",
    difficulty: "advanced",
    tags: ["negotiation", "leadership"],
    materials: [],
    mentorId: "108",
    feedback: [],
  },
  {
    id: "9",
    title: "Interview Preparation Essentials",
    description:
      "Prepare for interviews with confidence and land your dream job",
    categoryId: "2", // Another Career Development course
    categoryName: "Career Development",
    createdAt: "2024-09-05",
    updatedAt: "2024-11-03",
    status: "published",
    enrolledStudents: 40,
    completionRate: 95,
    dueDate: "2 weeks",
    difficulty: "beginner",
    tags: ["interview", "career"],
    materials: [],
    mentorId: "109",
    feedback: [],
  },
  {
    id: "10",
    title: "Agile Project Management",
    description: "Explore Agile methodologies for flexible project delivery",
    categoryId: "3", // Another Project Management course
    categoryName: "Project Management",
    createdAt: "2024-10-20",
    updatedAt: "2024-11-04",
    status: "published",
    enrolledStudents: 25,
    completionRate: 72,
    dueDate: "8 weeks",
    difficulty: "advanced",
    tags: ["agile", "project management"],
    materials: [],
    mentorId: "110",
    feedback: [],
  },
  {
    id: "11",
    title: "Presentation Design Tips",
    description: "Create visually engaging presentations",
    categoryId: "4", // Another Public Speaking course
    categoryName: "Public Speaking",
    createdAt: "2024-11-01",
    updatedAt: "2024-11-06",
    status: "published",
    enrolledStudents: 38,
    completionRate: 80,
    dueDate: "3 weeks",
    difficulty: "intermediate",
    tags: ["presentation", "public speaking"],
    materials: [],
    mentorId: "111",
    feedback: [],
  },
  {
    id: "12",
    title: "Prioritization Strategies",
    description: "Learn how to prioritize tasks effectively to achieve goals",
    categoryId: "5", // Another Time Management course
    categoryName: "Time Management",
    createdAt: "2024-10-10",
    updatedAt: "2024-11-07",
    status: "published",
    enrolledStudents: 45,
    completionRate: 90,
    dueDate: "2 weeks",
    difficulty: "beginner",
    tags: ["prioritization", "time management"],
    materials: [],
    mentorId: "112",
    feedback: [],
  },
];
