name: CI Automation Test - Build and Run Test

on:
  push:
    branches: main

defaults:
  run:
    working-directory: './AutomationTest'

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies & Playwright
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --grep "@SmokeTest"
        env:
          BASE_FE_URL: ${{ secrets.BASE_FE_URL }}
          BASE_BE_URL: ${{ secrets.BASE_BE_URL }}
          ADMIN_USER_NAME: ${{ secrets.ADMIN_USER_NAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          LEARNER_USER_NAME: ${{ secrets.LEARNER_USER_NAME }}
          LEARNER_PASSWORD: ${{ secrets.LEARNER_PASSWORD }}
          MENTOR_USER_NAME: ${{ secrets.MENTOR_USER_NAME }}
          MENTOR_PASSWORD: ${{ secrets.MENTOR_PASSWORD }}

      - name: Publish JUnit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: AutomationTest/test-results/*.xml

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: AutomationTest/test-results/html-report
